export const DEFAULT_THEMES = [
  {
    id: "soft_pearl",
    name: "Soft Rose Pearl",
    description: "Luminous pearl cream background with delicate rose gold accents",
    configuration: JSON.stringify({
      background: "bg-gradient-to-br from-[#FAF8F5] via-[#FFF5F7] to-[#F5EFE6]",
      cardBg: "bg-white/95 border-rose-200/60 shadow-xl",
      accent: "#E07A5F",
      textPrimary: "text-[#1F2937]",
      textSecondary: "text-[#E07A5F]",
      particleColor: "#F4ACB7",
      glowColor: "rgba(224, 122, 95, 0.25)",
      buttonStyle: "bg-gradient-to-r from-[#E07A5F] to-[#F4ACB7] text-white",
    }),
    previewImage: "https://images.unsplash.com/photo-1522383225653-ed111181a951?auto=format&fit=crop&w=400&q=80",
  },
  {
    id: "champagne_blossom",
    name: "Champagne Blossom",
    description: "Ethereal light ivory with warm golden amber sparkles",
    configuration: JSON.stringify({
      background: "bg-gradient-to-br from-[#FDFBF7] via-[#FFFBEB] to-[#FEF3C7]",
      cardBg: "bg-white/95 border-amber-200/80 shadow-xl",
      accent: "#D97706",
      textPrimary: "text-[#111827]",
      textSecondary: "text-[#D97706]",
      particleColor: "#FBBF24",
      glowColor: "rgba(217, 119, 6, 0.25)",
      buttonStyle: "bg-gradient-to-r from-[#F59E0B] to-[#D97706] text-white",
    }),
    previewImage: "https://images.unsplash.com/photo-1513151233558-d860c5398176?auto=format&fit=crop&w=400&q=80",
  },
];

export const DEFAULT_SONGS = [
  {
    id: "bgm_emotional_flute",
    title: "Emotional Flute & Piano BGM",
    artist: "Instrumental BGM",
    mood: "Emotional",
    genre: "BGM Instrumental",
    language: "Instrumental",
    energy: "Soft",
    duration: "2:45",
    audioUrl: "https://cdn.pixabay.com/download/audio/2022/05/27/audio_1808fbf07a.mp3",
    coverUrl: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=300&q=80",
  },
  {
    id: "bgm_acoustic_strings",
    title: "Nostalgic Acoustic Guitar BGM",
    artist: "Acoustic BGM",
    mood: "Nostalgic",
    genre: "Acoustic BGM",
    language: "Instrumental",
    energy: "Soft",
    duration: "3:10",
    audioUrl: "https://cdn.pixabay.com/download/audio/2022/03/15/audio_c8c8a7353f.mp3",
    coverUrl: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=300&q=80",
  },
  {
    id: "bgm_cinematic_orchestral",
    title: "Cinematic Sibling Memory BGM",
    artist: "Orchestral Score",
    mood: "Cinematic",
    genre: "Orchestral BGM",
    language: "Instrumental",
    energy: "Medium",
    duration: "2:30",
    audioUrl: "https://cdn.pixabay.com/download/audio/2022/01/18/audio_d0a13f69d2.mp3",
    coverUrl: "https://images.unsplash.com/photo-1465847899084-d164df4dedc6?auto=format&fit=crop&w=300&q=80",
  },
];
